version: '3'

services: 
  api:
    image: golang:1.18-alpine
    build: .
    command: go run api/main.go
    ports: 
      - 8000:8000

  prometheus:
    image: prom/prometheus:v2.21.0
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus

volumes:
  prometheus-data: